"""Phase-1 common scientific model and deterministic reference evaluator."""

from .candidate import apply_candidate, deduplicate_candidates
from .certifier import CertificationReport, certify_schedule
from .geometry import (
    DirectionResult,
    XSplitValidator,
    continuous_interference,
    frozen_handover_centers,
    finite_x_split_validator,
    generate_x_split_patterns,
    generate_y_split_patterns,
    optimize_directions,
    whole_eligible_rails,
    x_split_relation,
    x_split_geometry_metadata,
)
from .model import (
    CandidateKey,
    CandidateMove,
    CanonicalSolution,
    MoveType,
    OfficialMetrics,
    Operation,
    OperationKind,
    ParentWeld,
    Rail,
    RobotRoute,
    Route,
    ScheduleResult,
    ScheduleStatus,
    ScientificAmbiguityError,
    ScientificConfig,
    SplitKind,
    SplitPattern,
    WeldingBlock,
    FormalScope,
    FORMAL_SCOPE_V1,
    FORMAL_SCOPE_V1_1,
    EXPERIMENTAL_X_SPLIT_SCOPE_V1,
    ACTIVE_FORMAL_SCOPE,
    RunScientificIdentity,
    DEVELOPMENT_NO_REPAIR_V1,
    FORMAL_BOUNDED_DISPATCH_POLICY_V1,
    FORMAL_LIMITED_DISCREPANCY_DISPATCH_POLICY_V1,
)
from .oracle import (
    TinyOracleResult,
    tiny_scheduler_oracle,
    tiny_scheduler_oracle_from_templates,
)
from .provenance import (
    REPOSITORY_ID,
    SOURCE_PROVENANCE_POLICY_V1,
    SourceProvenance,
    SourceProvenanceError,
    canonicalize_repository_url,
    compute_source_tree_hash,
    resolve_source_provenance,
)
from .solution import canonicalize, official_metrics
from .scheduler import (
    SchedulerProfile,
    build_operation_templates,
    build_robot_routes,
    build_wait_for_graph,
    earliest_safe_start,
    earliest_safe_start_optimized,
    earliest_safe_start_slow,
    relevant_fixed_operations,
    reference_schedule,
    reference_schedule_optimized,
    reference_schedule_slow,
    reference_schedule_from_templates,
    reference_schedule_from_templates_optimized,
    reference_schedule_from_templates_slow,
    wait_for_cycles,
    reference_schedule_formal,
    reference_schedule_from_templates_formal,
    FormalReferenceEvaluator,
)

__all__ = [
    "FormalScope", "FORMAL_SCOPE_V1", "FORMAL_SCOPE_V1_1",
    "EXPERIMENTAL_X_SPLIT_SCOPE_V1",
    "ACTIVE_FORMAL_SCOPE", "RunScientificIdentity",
    "REPOSITORY_ID", "SOURCE_PROVENANCE_POLICY_V1", "SourceProvenance",
    "SourceProvenanceError", "canonicalize_repository_url",
    "compute_source_tree_hash", "resolve_source_provenance",
    "DEVELOPMENT_NO_REPAIR_V1", "FORMAL_BOUNDED_DISPATCH_POLICY_V1",
    "FORMAL_LIMITED_DISCREPANCY_DISPATCH_POLICY_V1",
    "reference_schedule_formal", "reference_schedule_from_templates_formal",
    "FormalReferenceEvaluator",
    "CertificationReport",
    "CandidateKey",
    "CandidateMove",
    "CanonicalSolution",
    "DirectionResult",
    "MoveType",
    "OfficialMetrics",
    "Operation",
    "OperationKind",
    "ParentWeld",
    "Rail",
    "RobotRoute",
    "Route",
    "ScheduleResult",
    "ScheduleStatus",
    "SchedulerProfile",
    "ScientificAmbiguityError",
    "ScientificConfig",
    "SplitKind",
    "SplitPattern",
    "TinyOracleResult",
    "WeldingBlock",
    "XSplitValidator",
    "apply_candidate",
    "build_operation_templates",
    "build_robot_routes",
    "build_wait_for_graph",
    "canonicalize",
    "certify_schedule",
    "continuous_interference",
    "deduplicate_candidates",
    "earliest_safe_start",
    "earliest_safe_start_optimized",
    "earliest_safe_start_slow",
    "frozen_handover_centers",
    "finite_x_split_validator",
    "generate_x_split_patterns",
    "generate_y_split_patterns",
    "official_metrics",
    "optimize_directions",
    "reference_schedule",
    "reference_schedule_optimized",
    "reference_schedule_slow",
    "reference_schedule_from_templates",
    "reference_schedule_from_templates_optimized",
    "reference_schedule_from_templates_slow",
    "relevant_fixed_operations",
    "tiny_scheduler_oracle",
    "tiny_scheduler_oracle_from_templates",
    "wait_for_cycles",
    "whole_eligible_rails",
    "x_split_relation",
    "x_split_geometry_metadata",
]
