"""Phase-1 common scientific model and deterministic reference evaluator."""

from .candidate import apply_candidate, deduplicate_candidates
from .certifier import CertificationReport, certify_schedule
from .geometry import (
    DirectionResult,
    continuous_interference,
    frozen_handover_centers,
    generate_x_split_patterns,
    generate_y_split_patterns,
    optimize_directions,
    whole_eligible_rails,
    x_split_relation,
)
from .model import (
    CandidateKey,
    CandidateMove,
    CanonicalSolution,
    MoveType,
    OfficialMetrics,
    Operation,
    OperationKind,
    ParentWeld,
    Rail,
    RobotRoute,
    Route,
    ScheduleResult,
    ScheduleStatus,
    ScientificAmbiguityError,
    ScientificConfig,
    SplitKind,
    SplitPattern,
    WeldingBlock,
)
from .oracle import TinyOracleResult, tiny_scheduler_oracle
from .solution import canonicalize, official_metrics
from .scheduler import (
    build_operation_templates,
    build_robot_routes,
    build_wait_for_graph,
    earliest_safe_start,
    reference_schedule,
    wait_for_cycles,
)

__all__ = [
    "CertificationReport",
    "CandidateKey",
    "CandidateMove",
    "CanonicalSolution",
    "DirectionResult",
    "MoveType",
    "OfficialMetrics",
    "Operation",
    "OperationKind",
    "ParentWeld",
    "Rail",
    "RobotRoute",
    "Route",
    "ScheduleResult",
    "ScheduleStatus",
    "ScientificAmbiguityError",
    "ScientificConfig",
    "SplitKind",
    "SplitPattern",
    "TinyOracleResult",
    "WeldingBlock",
    "apply_candidate",
    "build_operation_templates",
    "build_robot_routes",
    "build_wait_for_graph",
    "canonicalize",
    "certify_schedule",
    "continuous_interference",
    "deduplicate_candidates",
    "earliest_safe_start",
    "frozen_handover_centers",
    "generate_x_split_patterns",
    "generate_y_split_patterns",
    "official_metrics",
    "optimize_directions",
    "reference_schedule",
    "tiny_scheduler_oracle",
    "wait_for_cycles",
    "whole_eligible_rails",
    "x_split_relation",
]
