"""Deterministic minimal SA-OI-ALNS search backbone."""

from .direction import (
    ConstrainedDirectionResult,
    DirectionStatus,
    DirectionVectors,
    DirectionRefinementResult,
    optimize_directions_with_initial_feasibility,
    refine_directions_bounded,
)
from .stats import ACTIVE_MOVE_TYPES, SearchStats
from .initialization import (
    InitializationResult,
    InitializationStatus,
    InitializationStrategy,
    bounded_insertion_positions,
    build_initial_solution,
)
from .lns import (
    AdaptiveOperatorState,
    CandidateSourceKind,
    CompleteCandidateIdentity,
    CompleteSearchCandidate,
    DestroyOperator,
    PartialSearchState,
    RepairOperator,
    destroy_parents,
    destroy_size,
    repair_partial_state,
)
from .neighborhood import (
    RawAttempt,
    ScreenedCandidate,
    applicable_move_mask,
    balanced_move_attempt_order,
    generate_raw_attempts,
    screen_raw_attempts,
)
from .pipeline import (
    MicroGapResult,
    SearchConfig,
    SearchResult,
    SearchStatus,
    evaluate_iteration,
    micro_gap_decomposition,
    rerank_c3,
    run_bounded_sa_oi,
    sa_accept,
)

__all__ = [
    "ACTIVE_MOVE_TYPES",
    "ConstrainedDirectionResult",
    "DirectionStatus",
    "DirectionVectors",
    "DirectionRefinementResult",
    "AdaptiveOperatorState",
    "CandidateSourceKind",
    "CompleteCandidateIdentity",
    "CompleteSearchCandidate",
    "DestroyOperator",
    "PartialSearchState",
    "RepairOperator",
    "InitializationResult",
    "InitializationStatus",
    "InitializationStrategy",
    "MicroGapResult",
    "RawAttempt",
    "ScreenedCandidate",
    "SearchConfig",
    "SearchResult",
    "SearchStatus",
    "SearchStats",
    "applicable_move_mask",
    "balanced_move_attempt_order",
    "bounded_insertion_positions",
    "build_initial_solution",
    "evaluate_iteration",
    "generate_raw_attempts",
    "optimize_directions_with_initial_feasibility",
    "refine_directions_bounded",
    "destroy_parents",
    "destroy_size",
    "repair_partial_state",
    "micro_gap_decomposition",
    "rerank_c3",
    "run_bounded_sa_oi",
    "sa_accept",
    "screen_raw_attempts",
]
